---
- name: enable openlap server
  service:
    name: slapd
    enabled: true
  become: true
  notify:
    - start openldap server

- name: ensure firewalld is started
  service:
    name: firewalld
    enabled: true
  become: true
  notify:
    - start firewalld

- meta: flush_handlers
